"""
make_dev_candidates_csv.py — Generate DEV candidate CSV for coding quality scoring

Creates a DEV-CodingQuality-Candidates.csv that mirrors the PROD format
(from findcandidatesforexplore.sql / Athena export).

Columns: assigning_authority, qe, bucket, key, size, last_modified

Points at: s3://nyec.ccda.learning/TestDataForDeterminingLevelOfCodeSetQuality/
This is the folder with synthetic test CCDs that have data diversity
(generated by generate_test_cases.py with mutation profiles S/L/M/A/X).

In PROD: Athena query produces this from S3 inventory.
In DEV: We list the test data folder from S3 and build the same format.

The batch scorer reads this CSV to know which files to download and evaluate.
"""

import boto3
import csv
import json
import os

# Configuration
AWS_PROFILE = "student1"
BUCKET = "nyec.ccda.learning"
PREFIX = "TestDataForDeterminingLevelOfCodeSetQuality/"
MAX_FILES = None  # None = list ALL XMLs in the test folder

OUTPUT_CSV = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "DEV-Output",
    "DEV-CodingQuality-Candidates.csv"
)


def main():
    print(f"Connecting to S3 with profile '{AWS_PROFILE}'...")
    session = boto3.Session(profile_name=AWS_PROFILE)
    s3 = session.client("s3")

    print(f"Listing up to {MAX_FILES} XML files in s3://{BUCKET}/{PREFIX}...")
    xml_files = []
    paginator = s3.get_paginator("list_objects_v2")
    for page in paginator.paginate(Bucket=BUCKET, Prefix=PREFIX):
        for obj in page.get("Contents", []):
            key = obj["Key"]
            if key.lower().endswith(".xml"):
                xml_files.append({
                    "key": key,
                    "size": obj["Size"],
                    "last_modified": obj["LastModified"].strftime("%Y-%m-%d %H:%M:%S"),
                })
                if MAX_FILES and len(xml_files) >= MAX_FILES:
                    break
        if MAX_FILES and len(xml_files) >= MAX_FILES:
            break

    print(f"Found {len(xml_files)} XML files.")

    # Write CSV matching PROD Athena export format
    print(f"Writing to: {OUTPUT_CSV}")
    with open(OUTPUT_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, quoting=csv.QUOTE_ALL)
        writer.writerow([
            "assigning_authority",
            "qe",
            "bucket",
            "key",
            "size",
            "last_modified",
        ])

        for item in xml_files:
            # Get real QE/AA from the expected JSON sidecar (generated alongside test CCDs)
            expected_json_name = os.path.basename(item["key"]).replace(".xml", "_expected.json")
            expected_json_path = os.path.join(
                os.path.dirname(os.path.abspath(__file__)),
                "DEV-Output",
                "generated_test_cases",
                expected_json_name
            )
            
            qe = "(dev)"
            aa = "(dev-synthea)"
            if os.path.exists(expected_json_path):
                try:
                    with open(expected_json_path, "r", encoding="utf-8") as jf:
                        exp = json.load(jf)
                    source = exp.get("source", {})
                    qe = source.get("qe", "(dev)")
                    aa = source.get("assigning_authority", "(dev-synthea)")
                except Exception:
                    pass
            
            writer.writerow([
                aa,                # assigning_authority — from test case metadata
                qe,                # qe — from test case metadata
                BUCKET,            # bucket
                item["key"],       # key
                item["size"],      # size
                item["last_modified"],
            ])

    print(f"Done! Wrote {len(xml_files)} rows.")
    print(f"  Format: assigning_authority, qe, bucket, key, size, last_modified")
    print(f"  Ready for: score_ccd_coding_quality_batch.py")


if __name__ == "__main__":
    main()
